name: "Terraform CI/CD Workflow"

on:
  push:
    branches:
      - main  # Trigger on changes to main branch

env:
  ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
  ROOT_PATH: ${{ github.workspace }}/environments/dev

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Files in Workspace
        run: ls -R

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.ROOT_PATH }}

      - name: Terraform Format
        run: terraform fmt
        working-directory: ${{ env.ROOT_PATH }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.ROOT_PATH }}

      # -------------------------
      # **TFLint - Terraform Linting**
      # -------------------------
      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run TFLint
        run: |
          tflint --init
          tflint -f compact
        working-directory: ${{ env.ROOT_PATH }}

      # -------------------------
      # **TFSEC - Terraform Security Scanning**
      # -------------------------
      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec
        run: |
          tfsec --concise-output --soft-fail \
                --exclude-severity CRITICAL,MAJOR
        working-directory: ${{ env.ROOT_PATH }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ env.ROOT_PATH }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.ROOT_PATH }}
